name: docya_pro
description: Aplicación para médicos de DocYa Pro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


  
  


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0 
  geolocator: ^12.0.0   # 👈 agregado
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  web_socket_channel: ^2.4.0
  image_picker: ^1.0.7
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  signature: ^5.4.0
  http_parser: ^4.0.2
  awesome_snackbar_content: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logoblanco.png
    - assets/docyapro.png
    - assets/DOCYAPROBLANCO.png
